version: '3'

networks:
    laravel:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes:
            - ./backend/src:/var/www/app
            - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/dist:/var/www/frontend
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        platform: linux/amd64
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes:
            - ./backend/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: desafio_tasks
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            dockerfile: docker/Dockerfile.backend
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./backend/src:/var/www/app
        ports:
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks:
            - laravel

    frontend:
        build:
            dockerfile: docker/Dockerfile.frontend
        container_name: frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        depends_on:
            - php
        networks:
            - laravel